#dist: trusty

env:
  global:
    - XDEBUG_MODE=coverage

language: php

branches:
  only:
    - master
    - /[0-9]+\.[0-9]+\.[0-9]+/

cache:
  directories:
    - $HOME/.composer/cache/

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

matrix:
  allow_failures:
    - php: 8.1
    - php: nightly

#env:
#  matrix:
#    - COMPOSER_FLAGS="--prefer-lowest"
#    - COMPOSER_FLAGS=""

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-source

#before_script:
#  - phpenv config-rm xdebug.ini || true

script:
  - composer test
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text
