<?php

class PorTest extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWrite()
    {
        $this->assertFileExists('tmp/data.por');
    }

    /**
     * @after testWriteSav
     */
    public function testRead()
    {
        $this->assertFileExists('tmp/data.por');
    }
}