<?php

class SavTest extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWrite()
    {
        $this->assertFileExists('tmp/data.sav');
    }

    /**
     * @after testWriteSav
     */
    public function testRead()
    {
        $this->assertFileExists('tmp/data.sav');
    }
}